### ISSUE TITLE
Add a Section for Scholarships

### ISSUE THREAD

**Issue by HUIXIN-TW** [HUIXIN-TW/Portfolio#4]
**Issue Description:**
Add a new section for "Scholarships and Awards" to the project. This section will showcase your academic achievements from high school to postgraduate studies.

**Tasks to Complete:**
- [x] Create a new page or component for the "Scholarships and Awards" section.
- [x] Design the layout and structure of the section.
- [x] Populate the section with details about your scholarships and awards.
